const Map<String, String> translationsEnUs = {
  'Profile': 'Profile',
  'Change': 'Change',
  'Change language': 'Change language',
  'Change PIN': 'Change PIN',
  'Email': 'Email',
  'Name': 'Name',
  'Phone number': 'Phone number',
  'Birth date': 'Birth date',
  'English': 'English',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' Your have verified your ID card',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Account info': 'Account info',
  'Use Voucher': 'Use Voucher',
  'The use of vouchers cannot be combined with ':
      'The use of vouchers cannot be combined with ',
  'discount employee reward program': 'discount employee reward program',
  'oke': 'oke',
  'Delete': 'Delete',
  'Total Payment': 'Total Payment',
  'Order Now': 'Order Now',
  'Discount Info': 'Discount Info',
  'No discount available': 'No discount available',
  'Verify Order': 'Verify Order',
  'or': 'or',
  'Verify Using Pin': 'Verify Using Pin',
  'Order on Process': 'Order on Process',
  'You can track your order on feature': 'You can track your order on feature',
  'Order': 'Order',
  'Enter PIN Code': 'Enter PIN Code',
  'Detail Voucher': 'Detail Voucher',
  'Valid Date': 'Valid Date',
  'Choose Voucher': 'Choose Voucher',
  'Food': 'Food',
  'Beverage': 'Beverage',
  'Total Order': 'Total Order',
  'Discount': 'Discount',
  'Payment': 'Payment',
  'Pay Later': 'Pay Later',
  'Create Note': 'Create Note',
  'Note': 'Note',
  'Choose Level': 'Choose Level',
  'No Option Available': 'No Option Available',
  'Choose Topping': 'Choose Topping',
  'Menu Edit': 'Menu Edit',
  'Price': 'Price',
  'Updating': 'Updating',
  'Updating order on cart': 'Updating order on cart',
  'Getting menu data': 'Getting menu data',
  'Save': 'Save',
  'Finding Location...': 'Finding Location...',
  'Open settings': 'Open settings',
  'All Menu': 'All Menu',
  'Add Note': 'Add Note',
  'Search': 'Search',
  'Available Promo': 'Available Promo',
  'Menu Detail': 'Menu Detail',
  'Adding order': 'Adding order',
  'Oops There is no network': 'Oops There is no network',
  'Make sure connected to Wifi or Internet Celullar, then try again':
      'Make sure connected to Wifi or Internet Celullar, then try again',
  'Error': 'Error',
  'Still disconnected': 'Still disconnected',
  'Try Again': 'Try Again',
  'Email Address': 'Email Address',
  'Input Email Address': 'Input Email Address',
  'Email address cannot be empty': 'Email address cannot be empty',
  'Password': 'Password',
  'Input Password': 'Input Password',
  'Password cannot be empty': 'Password cannot be empty',
  'Login to continue!': 'Login to continue!',
  'Login': 'Login',
  'Login Using ': 'Login Using',
  'On Queue': 'On Queue',
  'Prepared': 'Prepared',
  'Ready': 'Ready',
  'Finished': 'Finished',
  'Canceled': 'Canceled',
  'Give Rating': 'Give Rating',
  'Order Again': 'Order Again',
  'On Going': 'On Going',
  'History': 'History',
  'Your order is being prepared': 'Your order is being prepared',
  'Order Received': 'Order Received',
  'Take it': 'Take it',
  'Order Finished': 'Order Finished',
  'Are you sure to cancel it ?': 'Are you sure to cancel it ?',
  'Cancel': 'Cancel',
  'Sure': 'Sure',
  'Cancel it': 'Cancel it',
  'Ordered? Track your order here.': 'Ordered? Track your order here.',
  'Start making an Order. The food you ordered will appear here so you can find your favorites again!':
      'Start making an Order. The food you ordered will appear here so you can find your favorites again!',
  'Promo Name': 'Promo Name',
  'Terms and Conditions': 'Terms and Conditions',
  'Review': 'Review',
  'Give Review!': 'Give Review!',
  'What can be improved?': 'What can be improved?',
  'Write Review': 'Write Review',
  'Write a review here...': 'Write a review here...',
  'Send Review': 'Send Review',
  'Home': 'Home',
  'Camera': 'Camera',
  'Gallery': 'Gallery',
  'Select image source': 'Select image source',
  'all menu': 'all menu',
  'food': 'food',
  'beverage': 'beverage',
  'Cropper': 'Cropper',
  'Profile Photo': 'Profile Photo',
  'ID Card': 'ID Card',
  'Success change profile photo': 'Success change profile photo',
  'Failed change profile photo': 'Failed change profile photo',
  'makanan': 'Food',
  'minuman': 'Beverage',
  'Adding Order': 'Adding Order',
  'Success to add order': 'Success to add order',
  'Failed to add order': 'Failed to add order'
};
