const Map<String, String> translationsIdId = {
  'Profile': 'Profil',
  'Change': 'Ubah',
  'Change language': 'Ubah bahasa',
  'Change PIN': 'Ubah PIN',
  'Email': 'Alamat Email',
  'Name': 'Nama',
  'Phone number': 'No. telepon',
  'Birth date': 'Tanggal lahir',
  'English': 'Inggris',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' KTP anda sudah terverifikasi',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Account info': 'Info Akun',
  'Use Voucher': 'Pakai Voucher',
  'The use of vouchers cannot be combined with ':
      'Penggunaan voucher tidak dapat digabung dengan ',
  'discount employee reward program': 'discount employee reward program',
  'oke': 'oke',
  'Delete': 'Hapus',
  'Total Payment': 'Total Pembayaran',
  'Order Now': 'Pesan Sekarang',
  'Discount Info': 'Info Diskon',
  'No discount available': 'Tidak ada diskon yang tersedia',
  'Verify Order': 'Verifikasi Pesanan',
  'or': 'atau',
  'Verify Using Pin': 'Verifikasi Menggunakan PIN',
  'Order on Process': 'Pesanan Sedang Disiapkan',
  'You can track your order on feature':
      'Kamu dapat melacak pesananmu di fitur',
  'Order': 'Pesanan',
  'Enter PIN Code': 'Masukkan kode PIN',
  'Voucher Detail': 'Detail Voucher',
  'Valid Date': 'Tanggal Valid',
  'Choose Voucher': 'Pilih Voucher',
  'Food': 'Makanan',
  'Beverage': 'Minuman',
  'Total Order': 'Total Pesanan',
  'Discount': 'Diskon',
  'Payment': 'Pembayaran',
  'Pay Later': 'Bayar Nanti',
  'Create Note': 'Buat Catatan',
  'Note': 'Catatan',
  'Choose Level': 'Pilih Level',
  'No Option Available': 'Tidak ada pilihan lain',
  'Choose Topping': 'Pilih Topping',
  'Menu Edit': 'Edit Menu',
  'Price': 'Harga',
  'Updating': 'Memperbarui',
  'Updating order on cart': 'Memperbarui pesanan di keranjang',
  'Getting menu data': 'Mendapatkan data menu',
  'Save': 'Simpan',
  'Finding Location...': 'Mencari Lokasimu...',
  'Open settings': 'Buka pengaturan',
  'All Menu': 'Semua Menu',
  'Add Note': 'Tambahkan Catatan',
  'Search': 'Pencarian',
  'Available Promo': 'Promo yang tersedia',
  'Menu Detail': 'Detail Menu',
  'Adding order': 'Tambahkan Pesanan',
  'Oops There is no network': 'Oops Tidak ada koneksi internet',
  'Make sure connected to Wifi or Internet Celullar, then try again':
      'Pastikan wifi atau data seluler terhubung, lalu tekan tombol coba lagi',
  'Error': 'Gagal',
  'Still disconnected': 'Masih belum terkoneksi',
  'Try Again': 'Coba Lagi',
  'Email Address': 'Alamat Email',
  'Input Email Address': 'Masukkan Alamat Email',
  'Email address cannot be empty': 'Alamat email tidak dapat kosong',
  'Password': 'Kata Sandi',
  'Input Password': 'Masukkan Kata Sandi',
  'Password cannot be empty': 'Password tidak dapat kosong',
  'Login to continue!': 'Masuk untuk melanjutkan!',
  'Login': 'Masuk',
  'Login Using ': 'Masuk Menggunakan',
  'On Queue': 'Dalam antrian',
  'Prepared': 'Sedang disiapkan',
  'Ready': 'Siap',
  'Finished': 'Selesai',
  'Canceled': 'Dibatalkan',
  'Give Rating': 'Beri Penilaian',
  'Order Again': 'Pesan Lagi',
  'On Going': 'Sedang Berjalan',
  'History': 'Riwayat',
  'Your order is being prepared': 'Pesanan kamu sedang disiapkan',
  'Order Received': 'Pesanan diterima',
  'Take it': 'Silahlkan Diambil',
  'Order Finished': 'Pesanan Selesai',
  'Are you sure to cancel it ?':
      'Apakah Anda yakin ingin membatalkan pesanan ini ?',
  'Cancel': 'Batal',
  'Sure': 'Yakin',
  'Cancel it': 'Batalkan',
  'Ordered? Track your order here.': 'Sudah Pesan? Lacak pesananmu di sini',
  'Start making an Order. The food you ordered will appear here so you can find your favorites again!':
      'Mulai buat Pesanan. Makanan yang kamu pesan akan muncul di sini agar kamu bisa menemukan menu favoritmu lagi!',
  'Promo Name': 'Nama Promo',
  'Terms and Conditions': 'Syarat Dan Ketentuan',
  'Review': 'Penilaian',
  'Give Review!': 'Beri Penilaian!',
  'What can be improved?': 'Apa yang bisa ditingkatkan?',
  'Write Review': 'Tulis Review',
  'Write a review here...': 'Tulis review disini...',
  'Send Review': 'Kirim Penilaian',
  'Home': 'Beranda',
  'Camera': 'Kamera',
  'Gallery': 'Galeri',
  'Select image source': 'Pilih sumber gambar',
  'all menu': 'semua menu',
  'food': 'makanan',
  'beverage': 'minuman',
  'Cropper': 'Pemotong',
  'Profile Photo': 'Foto Profil',
  'ID Card': 'Ktp',
  'Success change profile photo': 'Berhasil Mengganti Foto Profile',
  'Failed change profile photo': 'Gagal Mengganti Foto Profile',
  'Success validate KTP': 'Berhasil validasi KTP',
  'Failed validate KTP': 'Gagal validasi KTP',
  'makanan': 'makanan',
  'minuman': 'minuman',
  'Adding Order': 'Menambahkan Pesanan',
  'Success to add order': 'Berhasil Menambahkan Pesanan',
  'Failed to add order': 'Gagal Menambahkan Pesanan',
  'Name is required': 'Nama diperlukan',
  'Email is required': 'Email harus diisi',
  'Phone Number is required': 'Nomor telephone harus diisi',
  'Pin is required': 'Pin harus diisi',
    'Rating':'Penilaian',
  'Rate Now':'Nilai Sekarang',
  'Other info':'Informasi Lain',
  'Device Info':'Informasi Perangkat',
  'Device Version':'Versi Perangkat',
  'Log Out': 'Keluar',
  'Are you sure to logout ?':'Apakah yakin ingin keluar?',
  'Success to add review':'Berhasil menambahkan review'
};
