// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFamO80A_foi4Sz3GsZKMcKtkj2BvlVEs',
    appId: '1:749638894127:web:f2b763be3fe095739f7cda',
    messagingSenderId: '749638894127',
    projectId: 'core-venturo-4fcbe',
    authDomain: 'core-venturo-4fcbe.firebaseapp.com',
    storageBucket: 'core-venturo-4fcbe.appspot.com',
    measurementId: 'G-4WVHDKM5QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTr4wHZqk_O5vEr0UVB7OVMpHeRmbhsoM',
    appId: '1:749638894127:android:878c79540414a58f9f7cda',
    messagingSenderId: '749638894127',
    projectId: 'core-venturo-4fcbe',
    storageBucket: 'core-venturo-4fcbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgGdA1wITd7A19RM71Ddgfc1tU77Oc8U',
    appId: '1:749638894127:ios:e2a44764901032259f7cda',
    messagingSenderId: '749638894127',
    projectId: 'core-venturo-4fcbe',
    storageBucket: 'core-venturo-4fcbe.appspot.com',
    androidClientId: '749638894127-k3d59rk5f2grv1g8j6q2b3s1t6u2af7d.apps.googleusercontent.com',
    iosClientId: '749638894127-d06d8ntc7vslcsbdk1jk3g24bbrc1tcp.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsgGdA1wITd7A19RM71Ddgfc1tU77Oc8U',
    appId: '1:749638894127:ios:e2a44764901032259f7cda',
    messagingSenderId: '749638894127',
    projectId: 'core-venturo-4fcbe',
    storageBucket: 'core-venturo-4fcbe.appspot.com',
    androidClientId: '749638894127-k3d59rk5f2grv1g8j6q2b3s1t6u2af7d.apps.googleusercontent.com',
    iosClientId: '749638894127-d06d8ntc7vslcsbdk1jk3g24bbrc1tcp.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );
}
